// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMkqWBN8FVJpkYWlgTROH-CumAFvosF44',
    appId: '1:1018304997512:web:e585886dee7e10ce8f573d',
    messagingSenderId: '1018304997512',
    projectId: 'med2023-94215',
    authDomain: 'med2023-94215.firebaseapp.com',
    storageBucket: 'med2023-94215.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxCJ4u_WESv57EAqfVYBvywJDrWwb4eTE',
    appId: '1:1018304997512:android:6a663c1664e4cb938f573d',
    messagingSenderId: '1018304997512',
    projectId: 'med2023-94215',
    storageBucket: 'med2023-94215.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQyXbFkU9kY4B_SG2Ec_zYfhAnfBLE3nk',
    appId: '1:1018304997512:ios:106a7e33c4bb7e448f573d',
    messagingSenderId: '1018304997512',
    projectId: 'med2023-94215',
    storageBucket: 'med2023-94215.appspot.com',
    iosClientId: '1018304997512-7dqm9pp910kg3gq3f24jkr25566n7r6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQyXbFkU9kY4B_SG2Ec_zYfhAnfBLE3nk',
    appId: '1:1018304997512:ios:106a7e33c4bb7e448f573d',
    messagingSenderId: '1018304997512',
    projectId: 'med2023-94215',
    storageBucket: 'med2023-94215.appspot.com',
    iosClientId: '1018304997512-7dqm9pp910kg3gq3f24jkr25566n7r6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
